### ISSUE TITLE
JLS recovery does not always work

### ISSUE THREAD

**Issue by mliberty1** [jetperch/jls#10]
Version: 0.9.0 (feature/copy as of 2023-10-29)

When the JLS file is not closed, the recovery method kicks in on the next read.  However, we now get errors like this in the Joulescope UI:

```
Traceback (most recent call last):
  File "joulescope_ui\jls_source.py", line 157, in run
    rsp = self._jls.process(value)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "joulescope_ui\jls_v2.py", line 201, in process
    data = self._jls.fsr_statistics(signal_id, start, increment, length)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyjls/binding.pyx", line 706, in pyjls.binding.Reader.fsr_statistics
  File "pyjls/binding.pyx", line 268, in pyjls.binding._handle_rc
RuntimeError: rd_fsr_statistics IO[4]: Input/output error
ERROR:2023-10-28 12:47:12,537:core.c:774:pyjls.c:invalid index signal 2, level 3, sample_id=14323973 offset=157645328: 8 >= 8
ERROR:2023-10-28 12:47:12,537:jls_source.py:160:joulescope_ui.jls_source:During jls process
```

It appears either the repair did not work correctly or the signal information is not correct.

A workaround is to use the new `jls copy` command.  This command essentially replays the captured data into a new JLS file to recover from most errors.  You do need enough free drive space to store the copy, too.  

You can download the Windows `jls` executable [here](https://github.com/jetperch/jls/suites/17715228050/artifacts/1014149738).
Extract `jls.exe` from the contained cmake_build_static\example\Release directory.

The command on Windows is then:

    .\jls.exe copy <src> <dst>

Where you replace `<src>` and `<dst>` with the source JLS file and the destination JLS file.

Note that this command does not entirely work with current_range and the general purpose inputs.  These signals omit the low-level data when the value is constant, which the existing implementation does not replay correctly.  However, it already works great for current, voltage, and power.

**Comment by mliberty1** [comment]
Fixed in 0.9.2
